# Generated by Django 4.2.27 on 2026-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_equipement', models.CharField(choices=[('ORDINATEUR', 'Ordinateur (Portable/Fixe)'), ('ECRAN', 'Écran'), ('SERVEUR', 'Serveur'), ('SMARTPHONE', 'Smartphone')], max_length=20)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_acquisition', models.DateField()),
                ('consommation_estimee', models.FloatField(default=0, help_text='kWh/an')),
            ],
        ),
    ]
