# Generated by Django 4.2.27 on 2026-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipementnumerique',
            name='consommation_estimee',
        ),
        migrations.RemoveField(
            model_name='equipementnumerique',
            name='date_acquisition',
        ),
        migrations.AddField(
            model_name='equipementnumerique',
            name='consommation_annuelle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='equipementnumerique',
            name='duree_vie',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='equipementnumerique',
            name='empreinte_fabrication',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='equipementnumerique',
            name='type_equipement',
            field=models.CharField(choices=[('LAPTOP', 'Ordinateur Portable'), ('DESKTOP', 'Ordinateur Fixe'), ('SCREEN', 'Écran'), ('SERVER', 'Serveur'), ('PHONE', 'Smartphone')], max_length=20),
        ),
    ]
