# Generated by Django 4.2.27 on 2026-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerique', '0002_remove_equipementnumerique_consommation_estimee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementnumerique',
            name='consommation_annuelle',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='equipementnumerique',
            name='type_equipement',
            field=models.CharField(choices=[('LAPTOP', 'Ordinateur Portable'), ('DESKTOP', 'Ordinateur Fixe'), ('SCREEN', 'Écran'), ('SERVER', 'Serveur')], max_length=20),
        ),
    ]
