# Generated by Django 4.2.27 on 2026-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerique', '0003_alter_equipementnumerique_consommation_annuelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementnumerique',
            name='type_equipement',
            field=models.CharField(choices=[('HARDWARE', (('LAPTOP', 'Ordinateur Portable'), ('DESKTOP', 'Ordinateur Fixe + Écran'), ('SMARTPHONE', 'Smartphone / Tablette'))), ('NETWORK', (('WIFI', 'Borne Wi-Fi'), ('SWITCH', 'Switch réseau'))), ('CLOUD', (('CLOUD_VM', 'Instance Cloud / Serveur virtuel'), ('CLOUD_STO', 'Stockage Cloud 1 To'))), ('PERIPHERALS', (('PRINTER', 'Imprimante Laser'), ('SCREEN_ADD', 'Écran supplémentaire')))], max_length=20),
        ),
    ]
