# Generated by Django 4.2.27 on 2026-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerique', '0004_alter_equipementnumerique_type_equipement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementnumerique',
            name='type_equipement',
            field=models.CharField(choices=[('1. Hardware (Terminaux)', (('LAPTOP', 'Ordinateur Portable (250kg CO2e)'), ('DESKTOP_SCREEN', 'Ordinateur Fixe + Écran (350kg CO2e)'), ('SMARTPHONE', 'Smartphone / Tablette (50kg CO2e)'))), ('2. Réseau', (('BORNE_WIFI', 'Borne Wi-Fi (20kg CO2e)'), ('SWITCH', 'Switch réseau (80kg CO2e)'))), ('3. Cloud & Services', (('CLOUD_INSTANCE', 'Instance Cloud / Serveur virtuel (500kg CO2e)'), ('CLOUD_STORAGE', 'Stockage Cloud 1 To (150kg CO2e)'))), ('4. Périphériques', (('PRINTER', 'Imprimante Laser (500kg CO2e)'), ('SCREEN_EXTRA', 'Écran supplémentaire (200kg CO2e)')))], max_length=30),
        ),
    ]
