# Generated by Django 5.0.1 on 2026-01-16 14:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('category', models.CharField(choices=[('fuel', 'Carburant'), ('vehicle_km', 'Véhicule par km')], max_length=50, verbose_name='Catégorie')),
                ('subcategory', models.CharField(blank=True, help_text='Ex: essence, gazole, voiture_thermique', max_length=100, verbose_name='Sous-catégorie')),
                ('unit', models.CharField(help_text='L, km, kWh, etc.', max_length=20, verbose_name='Unité')),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='kg CO₂e par unité', max_digits=10, verbose_name="Facteur d'émission")),
                ('source', models.CharField(default='ADEME Base Carbone', max_length=200, verbose_name='Source')),
                ('source_url', models.URLField(blank=True, verbose_name='URL source')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valide depuis')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Vérifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Facteur d'émission",
                'verbose_name_plural': "Facteurs d'émission",
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024, verbose_name='Année')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service/Direction')),
                ('calculation_method', models.CharField(choices=[('fuel', 'Par carburant'), ('distance', 'Par distance')], default='fuel', max_length=20, verbose_name='Méthode de calcul')),
                ('essence_liters', models.DecimalField(blank=True, decimal_places=2, help_text="Consommation totale d'essence en litres", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Essence (litres)')),
                ('gazole_liters', models.DecimalField(blank=True, decimal_places=2, help_text='Consommation totale de gazole en litres', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gazole (litres)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance totale parcourue en kilomètres', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Distance (km)')),
                ('total_co2_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Impact carbone total en kg CO₂e', max_digits=12, null=True, verbose_name='Total CO₂ (kg)')),
                ('essence_co2_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='CO₂ Essence (kg)')),
                ('gazole_co2_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='CO₂ Gazole (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Donnée véhicule',
                'verbose_name_plural': 'Données véhicules',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'year', 'service')},
            },
        ),
    ]
