# Generated by Django 4.2.27 on 2026-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Année'),
        ),
    ]
